# Generated by Django 3.2.4 on 2021-07-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.answertype'),
        ),
        migrations.AlterField(
            model_name='answertype',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
