# Generated by Django 3.2.4 on 2021-08-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210704_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsAddingFromFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models.question',),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='answertype',
            table='answers_types',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
