# Generated by Django 3.2.4 on 2021-10-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20210820_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionsAddingFromFile',
        ),
        migrations.CreateModel(
            name='QuestionsFromFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models.question',),
        ),
    ]
