# Generated by Django 3.2.4 on 2022-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20211004_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='period',
        ),
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
