version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=his_database_pol
      - POSTGRES_USER=hist_user
      - POSTGRES_PASSWORD=haslo12345
  web:
    build: .
    command: >
      bash -c "
      pip install -r requirements.txt
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
